# Generated by Django 4.1.2 on 2023-01-12 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
        ('Daily_sell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sellm',
            name='waiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='waiter', to='Employees.waiter'),
            preserve_default=False,
        ),
    ]
