# Generated by Django 4.1.2 on 2022-12-30 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu_items',
        ),
    ]
