# Generated by Django 4.1.2 on 2022-12-30 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingr_name', models.CharField(max_length=20)),
                ('ingr_type', models.CharField(max_length=20)),
                ('country', models.ForeignKey(default='not specified', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='Menu.country')),
            ],
        ),
        migrations.AddField(
            model_name='menu_items',
            name='country',
            field=models.ForeignKey(default='not especified', on_delete=django.db.models.deletion.CASCADE, related_name='Menu', to='Menu.country'),
        ),
    ]
