# Generated by Django 4.1.2 on 2023-01-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_caracteristict'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caracteristict',
            new_name='Characteristict',
        ),
    ]
